#!/bin/sh
set -e

PREREQS=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

##
copy_exec /sbin/sfdisk /sbin
copy_exec /usr/bin/growpart /sbin
copy_exec /sbin/udevadm /sbin

# vi: ts=4 noexpandtab
